import { ProblemSolution, NgoProfile, DonationType } from './types';
import { 
  Search, 
  MapPin, 
  BarChart3, 
  Heart, 
  Navigation, 
  ShieldCheck, 
  Smartphone, 
  Truck 
} from 'lucide-react';

export const APP_NAME = "ShareCare Connect";

// Extracted directly from the provided images
export const PROBLEM_SOLUTIONS: ProblemSolution[] = [
  {
    id: 1,
    problem: "Donors often wish to help but don't know which NGOs to contact or where to donate.",
    solution: "A centralized platform that connects donors and NGOs with pickup or drop-off options.",
    iconName: "Search"
  },
  {
    id: 2,
    problem: "Donors lack visibility into what happens to their contributions after donating.",
    solution: "Tracking system with unique donation IDs for transparency.",
    iconName: "Navigation"
  },
  {
    id: 3,
    problem: "Some NGOs receive excess clothes while others lack stationery supplies.",
    solution: "Data insights to monitor donation patterns and balance distribution.",
    iconName: "BarChart3"
  },
  {
    id: 4,
    problem: "Potential donors don't realize how their small contributions can help.",
    solution: "Awareness section with impact stories and visuals generated by AI.",
    iconName: "Heart"
  },
  {
    id: 5,
    problem: "Certain communities rarely receive help due to poor coordination.",
    solution: "Mapping underserved areas and guiding donations accordingly.",
    iconName: "MapPin"
  },
  {
    id: 6,
    problem: "Donors hesitate due to fake or inactive NGOs misusing platforms.",
    solution: "Verified NGO profiles with ratings and authenticity checks.",
    iconName: "ShieldCheck"
  },
  {
    id: 7,
    problem: "Less tech-savvy users struggle to use complex donation sites.",
    solution: "Mobile-friendly, multilingual, and simple interface.",
    iconName: "Smartphone"
  },
  {
    id: 8,
    problem: "Coordinating pickups and deliveries is time-consuming and confusing.",
    solution: "Automated matching and scheduling for smooth logistics.",
    iconName: "Truck"
  }
];

export const MOCK_NGOS: NgoProfile[] = [
  {
    id: "ngo-1",
    name: "EduCare Foundation",
    verified: true,
    rating: 4.8,
    focus: [DonationType.STATIONERY, DonationType.BOOKS],
    location: "North District",
    description: "Focusing on literacy and education for underprivileged children."
  },
  {
    id: "ngo-2",
    name: "Warmth for All",
    verified: true,
    rating: 4.9,
    focus: [DonationType.CLOTHES],
    location: "East Side",
    description: "Collecting winter wear and daily clothes for homeless shelters."
  },
  {
    id: "ngo-3",
    name: "Play & Learn",
    verified: true,
    rating: 4.5,
    focus: [DonationType.TOYS, DonationType.BOOKS],
    location: "Central City",
    description: "Ensuring every child has a happy childhood with toys and learning materials."
  }
];

export const MOCK_IMPACT_DATA = [
  { name: 'Stationery', value: 400, need: 600 },
  { name: 'Clothes', value: 300, need: 200 },
  { name: 'Books', value: 200, need: 300 },
  { name: 'Toys', value: 100, need: 150 },
];
